// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57oiGVqgLDKfTnAom_84DK2G3lau0qts',
    appId: '1:276555512555:web:cb0fcd211e6eabf7d6dcae',
    messagingSenderId: '276555512555',
    projectId: 'chat-52f38',
    authDomain: 'chat-52f38.firebaseapp.com',
    storageBucket: 'chat-52f38.appspot.com',
    measurementId: 'G-VKC4EYSJJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6RrF85SXNtDDObbKnzjBlEtEEttXoQDY',
    appId: '1:276555512555:android:b9cbb010af0cc62cd6dcae',
    messagingSenderId: '276555512555',
    projectId: 'chat-52f38',
    storageBucket: 'chat-52f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPmvRle1-iVevysV9wiefvUk0na9G4Sg',
    appId: '1:276555512555:ios:15d57377fb3e126ad6dcae',
    messagingSenderId: '276555512555',
    projectId: 'chat-52f38',
    storageBucket: 'chat-52f38.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPmvRle1-iVevysV9wiefvUk0na9G4Sg',
    appId: '1:276555512555:ios:2084e7ebbcccc68bd6dcae',
    messagingSenderId: '276555512555',
    projectId: 'chat-52f38',
    storageBucket: 'chat-52f38.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
